
export DEMO_LOGGER_MAXLEN=999
export DEMO_CLIENT_BASEURI=http://localhost:8500
export DEMO_CLIENT_TIMEOUT=9m
export DEMO_CLIENT_TIMEOUTSHORT=9m

export DEMO_SERVER_PORT=8081
export DEMO_DISCOVER_KEY="services-test"
